version: "3.3"
services:
  geoserver:
    image: kartoza/geoserver:2.13.0
    volumes:
      - geoserver:/opt/geoserver/data_dir:Z
      - ./geoserver/plugins/:/opt/geoserver/geoserver-exts/:Z
    ports:
      - "8088:8080"
    depends_on:
      - postgis
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    container_name: copernicus-geoserver
    networks:
      - gis
  postgis:
    image: mdillon/postgis:11
    volumes:
      - postgres_database:/var/lib/postgresql/data:Z
    ports:
      - "5434:5432"
    restart: on-failure    
    container_name: copernicus-postgis
    networks:
      - gis

networks:
  gis:
    driver: bridge

volumes:
    postgres_database:
        external: true
    geoserver:
        external: true          